<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Nettoyer les anciens produits
        Product::truncate();

        $products = [
            // ─── MEUBLES ──────────────────────────────────────────────────────
            [
                'name'          => "Salon Complet 7 Places — Velours Gris Anthracite",
                'price'         => 485000,
                'old_price'     => 550000,
                'image'         => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Meubles',
                'rating'        => 5,
                'reviews_count' => 134,
                'location'      => 'Douala, Akwa',
                'is_featured'   => true,
                'badge'         => '-12%',
                'status'        => 'active',
                'description'   => 'Salon haut de gamme 7 places en velours gris anthracite. Livraison et montage inclus à Douala.',
            ],
            [
                'name'          => "Lit 2 Places avec Coffre de Rangement — 160×200",
                'price'         => 280000,
                'old_price'     => 320000,
                'image'         => 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Meubles',
                'rating'        => 4,
                'reviews_count' => 87,
                'location'      => 'Yaoundé, Bastos',
                'is_featured'   => true,
                'badge'         => 'Bestseller',
                'status'        => 'active',
                'description'   => 'Lit 160×200 avec coffre de rangement intégré, tête de lit capitonnée. Idéal pour appartements.',
            ],
            [
                'name'          => "Armoire 4 Portes Battantes — Chêne Naturel",
                'price'         => 195000,
                'old_price'     => null,
                'image'         => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Meubles',
                'rating'        => 4,
                'reviews_count' => 52,
                'location'      => 'Douala, Bonapriso',
                'is_featured'   => false,
                'badge'         => null,
                'status'        => 'active',
                'description'   => 'Grande armoire 4 portes en chêne naturel avec miroir intégré. Capacité 280L.',
            ],
            [
                'name'          => "Table à Manger 6 Personnes — Marbre & Métal",
                'price'         => 340000,
                'old_price'     => 380000,
                'image'         => 'https://images.unsplash.com/photo-1604578762246-41134e37f9cc?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Meubles',
                'rating'        => 5,
                'reviews_count' => 61,
                'location'      => 'Yaoundé, Omnisports',
                'is_featured'   => true,
                'badge'         => 'Premium',
                'status'        => 'active',
                'description'   => 'Table à manger design en plateau marbre blanc et pieds métalliques dorés. 6 couverts.',
            ],
            [
                'name'          => "Table Basse en Verre Trempé Fumé",
                'price'         => 85000,
                'old_price'     => 95000,
                'image'         => 'https://images.unsplash.com/photo-1550254478-ead40cc54513?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Meubles',
                'rating'        => 4,
                'reviews_count' => 45,
                'location'      => 'Yaoundé, Mvan',
                'is_featured'   => false,
                'badge'         => null,
                'status'        => 'active',
                'description'   => 'Table basse plateau verre trempé fumé sur structure acier inoxydable brossé.',
            ],
            [
                'name'          => "Bureau Ergonomique avec Retour — Effet Bois Wengé",
                'price'         => 145000,
                'old_price'     => null,
                'image'         => 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Meubles',
                'rating'        => 4,
                'reviews_count' => 38,
                'location'      => 'Douala, Makepe',
                'is_featured'   => false,
                'badge'         => 'Nouveau',
                'status'        => 'active',
                'description'   => 'Bureau en L avec retour, tiroirs de rangement et surface en effet wengé. Idéal télétravail.',
            ],

            // ─── ÉLECTROMÉNAGER ───────────────────────────────────────────────
            [
                'name'          => "Réfrigérateur Combiné 400L — Samsung NoFrost",
                'price'         => 380000,
                'old_price'     => 420000,
                'image'         => 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Électroménager',
                'rating'        => 5,
                'reviews_count' => 203,
                'location'      => 'Douala, Akwa',
                'is_featured'   => true,
                'badge'         => '-10%',
                'status'        => 'active',
                'description'   => 'Réfrigérateur Samsung 400L No Frost, classe A++. Adapté aux variations électriques camerounaises.',
            ],
            [
                'name'          => "Machine à Laver 7kg — LG Direct Drive",
                'price'         => 295000,
                'old_price'     => null,
                'image'         => 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Électroménager',
                'rating'        => 4,
                'reviews_count' => 112,
                'location'      => 'Yaoundé, Biyem-Assi',
                'is_featured'   => false,
                'badge'         => null,
                'status'        => 'active',
                'description'   => 'Lave-linge LG 7kg Direct Drive. 14 programmes, protection contre les surtensions.',
            ],
            [
                'name'          => "Télévision 55\" 4K UHD — Hisense QLED",
                'price'         => 320000,
                'old_price'     => 360000,
                'image'         => 'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Électroménager',
                'rating'        => 5,
                'reviews_count' => 178,
                'location'      => 'Douala, Bonanjo',
                'is_featured'   => true,
                'badge'         => 'Promo',
                'status'        => 'active',
                'description'   => 'Smart TV Hisense 55 pouces QLED 4K. Android TV, Dolby Audio. Compatible DSTV & Netflix.',
            ],
            [
                'name'          => "Cuisinière Gaz 4 Feux + Four — Brandt",
                'price'         => 185000,
                'old_price'     => 210000,
                'image'         => 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Électroménager',
                'rating'        => 4,
                'reviews_count' => 95,
                'location'      => 'Yaoundé, Elig-Essono',
                'is_featured'   => false,
                'badge'         => '-12%',
                'status'        => 'active',
                'description'   => 'Cuisinière Brandt 4 feux gaz avec four électrique intégré. Grille-pain, allumage automatique.',
            ],

            // ─── CLIMATISATION ────────────────────────────────────────────────
            [
                'name'          => "Climatiseur Split 12000 BTU — Midea Inverter",
                'price'         => 220000,
                'old_price'     => 260000,
                'image'         => 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Climatisation',
                'rating'        => 5,
                'reviews_count' => 317,
                'location'      => 'Douala, Makepe',
                'is_featured'   => true,
                'badge'         => 'Top Vente',
                'status'        => 'active',
                'description'   => 'Clim Midea 12000 BTU Inverter A++. Installation comprises dans les quartiers de Douala. Idéal chambre 20m².',
            ],
            [
                'name'          => "Climatiseur Cassette 24000 BTU — Daikin",
                'price'         => 650000,
                'old_price'     => null,
                'image'         => 'https://images.unsplash.com/photo-1558618047-f4f2b8e5e3ee?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Climatisation',
                'rating'        => 5,
                'reviews_count' => 42,
                'location'      => 'Yaoundé, Bastos',
                'is_featured'   => false,
                'badge'         => 'Professionnel',
                'status'        => 'active',
                'description'   => 'Climatiseur cassette Daikin 24000 BTU pour espaces de bureau ou salons >40m². Installation sur mesure.',
            ],

            // ─── SÉCURITÉ ─────────────────────────────────────────────────────
            [
                'name'          => "Kit Vidéosurveillance 8 Caméras HD — avec DVR",
                'price'         => 185000,
                'old_price'     => 220000,
                'image'         => 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Sécurité',
                'rating'        => 5,
                'reviews_count' => 210,
                'location'      => 'Douala, Bonapriso',
                'is_featured'   => true,
                'badge'         => 'Promo',
                'status'        => 'active',
                'description'   => 'Kit 8 caméras 2MP Full HD + DVR 8 canaux + disque 1To. Vision nocturne 30m. Installation offerte à Douala.',
            ],
            [
                'name'          => "Serrure Connectée Biométrique + Code",
                'price'         => 95000,
                'old_price'     => 115000,
                'image'         => 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Sécurité',
                'rating'        => 4,
                'reviews_count' => 88,
                'location'      => 'Douala, Akwa',
                'is_featured'   => false,
                'badge'         => '-17%',
                'status'        => 'active',
                'description'   => 'Serrure connectée empreinte digitale + code + télécommande. Compatible SFT et compatible toutes portes. App mobile incluse.',
            ],
            [
                'name'          => "Alarme Maison Sans Fil — GSM + Wi-Fi",
                'price'         => 65000,
                'old_price'     => null,
                'image'         => 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Sécurité',
                'rating'        => 4,
                'reviews_count' => 73,
                'location'      => 'Yaoundé, Nlongkak',
                'is_featured'   => false,
                'badge'         => 'Nouveau',
                'status'        => 'active',
                'description'   => 'Alarme sans fil GSM/Wi-Fi avec détecteurs de mouvement, capteur porte et sirène 120dB. App mobile.',
            ],

            // ─── ÉCLAIRAGE ────────────────────────────────────────────────────
            [
                'name'          => "Lustre Suspendu LED Moderne — Or Brossé Ø60cm",
                'price'         => 78000,
                'old_price'     => 95000,
                'image'         => 'https://images.unsplash.com/photo-1513506003901-1e6a35a10568?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Éclairage',
                'rating'        => 5,
                'reviews_count' => 134,
                'location'      => 'Yaoundé, Bastos',
                'is_featured'   => true,
                'badge'         => '-18%',
                'status'        => 'active',
                'description'   => 'Lustre design or brossé Ø60cm avec LED intégrées 3000K. Idéal salon ou salle à manger. Compatible variateur.',
            ],
            [
                'name'          => "Lampe sur Pied Trépied — Design Industriel",
                'price'         => 45000,
                'old_price'     => null,
                'image'         => 'https://images.unsplash.com/photo-1568495248636-6432b97bd949?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Éclairage',
                'rating'        => 4,
                'reviews_count' => 56,
                'location'      => 'Douala, Bali',
                'is_featured'   => false,
                'badge'         => null,
                'status'        => 'active',
                'description'   => 'Lampe trépied design industriel, hauteur réglable 140-180cm. Ampoule E27 incluse 12W.',
            ],

            // ─── DÉCORATION ───────────────────────────────────────────────────
            [
                'name'          => "Tableau Décoratif Triptyque — Savane Africaine",
                'price'         => 55000,
                'old_price'     => null,
                'image'         => 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Décoration',
                'rating'        => 5,
                'reviews_count' => 89,
                'location'      => 'Bafoussam',
                'is_featured'   => false,
                'badge'         => 'Artisanal',
                'status'        => 'active',
                'description'   => 'Set de 3 toiles imprimées représentant la savane africaine au coucher de soleil. Châssis en bois massif.',
            ],
            [
                'name'          => "Vase Céramique Artisanal — Collection Douala",
                'price'         => 25000,
                'old_price'     => null,
                'image'         => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Décoration',
                'rating'        => 5,
                'reviews_count' => 67,
                'location'      => 'Bafoussam',
                'is_featured'   => false,
                'badge'         => 'Artisan Local',
                'status'        => 'active',
                'description'   => 'Vase en céramique peinte à la main par des artisans de Bafoussam. Collection exclusive HMC Market.',
            ],
            [
                'name'          => "Miroir Mural Rond à Contour Doré — Ø80cm",
                'price'         => 68000,
                'old_price'     => 80000,
                'image'         => 'https://images.unsplash.com/photo-1526657782461-9fe13402a841?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Décoration',
                'rating'        => 4,
                'reviews_count' => 44,
                'location'      => 'Yaoundé, Bastos',
                'is_featured'   => true,
                'badge'         => '-15%',
                'status'        => 'active',
                'description'   => 'Miroir rond design avec contour métal doré. Diamètre 80cm. Parfait pour entrée ou salon.',
            ],

            // ─── ÉLECTRICITÉ / ÉNERGIE ────────────────────────────────────────
            [
                'name'          => "Onduleur 3KVA — APC Smart-UPS avec Batteries",
                'price'         => 420000,
                'old_price'     => 480000,
                'image'         => 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Énergie',
                'rating'        => 5,
                'reviews_count' => 156,
                'location'      => 'Douala, Bonanjo',
                'is_featured'   => true,
                'badge'         => 'Essentiel',
                'status'        => 'active',
                'description'   => 'APC Smart-UPS 3KVA avec batteries intégrées. Autonomie 4h pour ordinateurs et équipements bureautique. Indispensable au Cameroun.',
            ],
            [
                'name'          => "Groupe Électrogène 5 KVA — Insonorisé Yamaha",
                'price'         => 850000,
                'old_price'     => 950000,
                'image'         => 'https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&q=80&w=800',
                'category'      => 'Énergie',
                'rating'        => 5,
                'reviews_count' => 98,
                'location'      => 'Douala, Makepe',
                'is_featured'   => true,
                'badge'         => '-10%',
                'status'        => 'active',
                'description'   => 'Groupe électrogène Yamaha 5KVA insonorisé. Démarrage électrique, autonomie 10h. Parfait pour villa ou immeuble.',
            ],
        ];

        foreach ($products as $data) {
            Product::create($data);
        }

        $this->command->info('✅ ' . count($products) . ' produits marketplace créés avec succès !');
    }
}
